export const dummyData = [
  {
    id: 1,
    date: "Thu, 31 Jul 2025",
    transaction: " Direct Debit",
    amount: -6,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 4,
    date: "Mon, 21 Jul 2025",
    transaction: " Direct Debit",
    amount: -79.8,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 5,
    date: "Mon, 21 Jul 2025",
    transaction: " Card",
    amount: -14.93,
    description:
      "Card 63, Openai *Chatgpt Subscr, USD -20.00, Rate 0.746, Fee 0.00, Sterling Amount -14.93",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 7,
    date: "Thu, 17 Jul 2025",
    transaction: " Card",
    amount: -18.32,
    description:
      "Card 63, Anam.Ai, USD -24.50, Rate 0.748, Fee 0.00, Sterling Amount -18.32",
    vat: true,
    category: "Accountants",
  },
  {
    id: 10,
    date: "Fri, 11 Jul 2025",
    transaction: " Card",
    amount: -3.7,
    description:
      "Card 63, Openai, USD -5.00, Rate 0.74, Fee 0.00, Sterling Amount -3.70",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 12,
    date: "Thu, 10 Jul 2025",
    transaction: " Card",
    amount: -46.14,
    description:
      "Card 63, Heygen Technology Inc., USD -62.40, Rate 0.739, Fee 0.00, Sterling Amount -46.14",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 13,
    date: "Wed, 09 Jul 2025",
    transaction: " Card",
    amount: -6.34,
    description: "Card 63, Amazon.Co.Uk*Rc2Et9B74",
    vat: true,
    category: "Consumables",
  },
  {
    id: 15,
    date: "Thu, 03 Jul 2025",
    transaction: " Card",
    amount: -12,
    description: "Card 63, Freelancer* O #25038",
    vat: false,
    category: "Training material",
  },
  {
    id: 16,
    date: "Mon, 30 Jun 2025",
    transaction: " Direct Debit",
    amount: -6,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 18,
    date: "Wed, 25 Jun 2025",
    transaction: " Card",
    amount: -69.04,
    description: "Card 63, Safe.Co.Uk",
    vat: true,
    category: "Consumables",
  },
  {
    id: 20,
    date: "Mon, 23 Jun 2025",
    transaction: " Direct Debit",
    amount: -79.8,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 21,
    date: "Mon, 23 Jun 2025",
    transaction: " Card",
    amount: -14.95,
    description:
      "Card 63, Openai *Chatgpt Subscr, USD -20.00, Rate 0.748, Fee 0.00, Sterling Amount -14.95",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 23,
    date: "Mon, 16 Jun 2025",
    transaction: " Giro",
    amount: 79.84,
    description: "S0651633121A01     PRINCE GALLERY V/E",
    vat: false,
    category: "Invoices",
  },
  {
    id: 25,
    date: "Tue, 10 Jun 2025",
    transaction: " Card",
    amount: -35.68,
    description:
      "Card 63, Heygen Technology Inc., USD -48.18, Rate 0.741, Fee 0.00, Sterling Amount -35.68",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 26,
    date: "Tue, 10 Jun 2025",
    transaction: " Giro",
    amount: 300,
    description: "UNIVERSITY OF NOTT 50705",
    vat: true,
    category: "Invoices",
  },
  {
    id: 28,
    date: "Mon, 02 Jun 2025",
    transaction: " Direct Debit",
    amount: -6,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 31,
    date: "Thu, 29 May 2025",
    transaction: " Card",
    amount: -17.19,
    description:
      "Card 63, Heygen Technology Inc., USD -23.20, Rate 0.741, Fee 0.00, Sterling Amount -17.19",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 33,
    date: "Tue, 27 May 2025",
    transaction: " Card",
    amount: -14.99,
    description: "Card 63, Udemy",
    vat: true,
    category: "Training material",
  },
  {
    id: 35,
    date: "Wed, 21 May 2025",
    transaction: " Direct Debit",
    amount: -79.8,
    description: "Gocardless, ACCOUNTANTS-3AP45J",
    vat: true,
    category: "Accountants",
  },
  {
    id: 36,
    date: "Wed, 21 May 2025",
    transaction: " Card",
    amount: -15.09,
    description:
      "Card 63, Openai *Chatgpt Subscr, USD -20.00, Rate 0.754, Fee 0.00, Sterling Amount -15.09",
    vat: false,
    category: "Subscriptions",
  },
  {
    id: 37,
    date: "Thurs, 22 May 2025",
    transaction: " Card",
    amount: -10,
    description:
      "Card 63, Openai *Chatgpt Subscr, USD -20.00, Rate 0.754, Fee 0.00, Sterling Amount -15.09",
    vat: true,
    category: "Consumables",
  },
  {
    id: 39,
    date: "Wed, 14 May 2025",
    transaction: " Transfer",
    amount: 400,
    description: "FPS, Toc Systems Sl, DRT-TO-001",
    vat: false,
    category: "Invoices",
  },
  {
    id: 40,
    date: "Fri, 09 May 2025",
    transaction: " Giro",
    amount: 3000,
    description: "UNIVERSITY OF NOTT 43864",
    vat: true,
    category: "Invoices",
  },
];
